name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#  push:
#    tags:
#      - 'v*.*.*'

jobs:
  # build-dev
  build-dev:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3

      # 创建构建后的liblcl二进制压缩包存放目录和设置git仓库
      - name: Config liblcl
        run: |
          touch test.txt
          sudo mkdir /app
          sudo cp test.txt /app/
